import { Timestamp } from 'firebase/firestore';

/**
 * Creates a unified request structure for requestsV2 collection
 */
export const createUnifiedRequest = (requestType, baseData, typeSpecificData = {}) => {
    return {
        // Core identification
        id: null, // Auto-generated by Firestore
        type: requestType,
        status: 'SUBMITTED',
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
        
        // User and assignment info
        franchiseId: baseData.franchiseId,
        franchiseName: baseData.franchiseName,
        franchiseCode: baseData.franchiseCode,
        submittedBy: baseData.submittedBy,
        assignedTo: baseData.assignedTo || 'Sales Team',
        
        // Device tracking
        deviceInfo: {
            imei: baseData.imei || null,
            currentStatus: 'MAPPED',
            currentBdoId: baseData.bdoId || null,
            previousBdoId: null // For transfers
        },
        
        // BDO information
        bdoInfo: {
            bdoId: baseData.bdoId || null,
            bdoName: baseData.bdoName || null,
            cnicNumber: baseData.cnicNumber || null,
            otpMobileNumber: baseData.otpMobileNumber || null,
            handlerType: baseData.handlerType || null
        },
        
        // Location information
        locationInfo: {
            shopName: baseData.shopName || null,
            city: baseData.city || null,
            streetAddress: baseData.streetAddress || null,
            coordinates: {
                latitude: parseFloat(baseData.latitude) || null,
                longitude: parseFloat(baseData.longitude) || null
            },
            premiseRelationship: baseData.premiseRelationship || null
        },
        
        // Documents
        documents: baseData.documents || {},
        
        // Workflow tracking
        workflowHistory: [
            {
                status: 'SUBMITTED',
                timestamp: Timestamp.now(),
                updatedBy: baseData.submittedBy,
                comments: 'Request submitted',
                userRole: baseData.userRole || 'Franchise'
            }
        ],
        
        // Type-specific data
        requestData: typeSpecificData,
        
        // Lifecycle metadata
        lifecycleMetadata: {
            totalStatusChanges: 1,
            lastTransferDate: null,
            daysInCurrentStatus: 0,
            totalActiveDays: 0
        },
        
        // Legacy fields for backward compatibility (keep existing structure)
        imei: baseData.imei || null,
        bdoId: baseData.bdoId || null,
        bdoName: baseData.bdoName || null,
        shopName: baseData.shopName || null,
        city: baseData.city || null,
        streetAddress: baseData.streetAddress || null,
        latitude: baseData.latitude || null,
        longitude: baseData.longitude || null,
        premiseRelationship: baseData.premiseRelationship || null,
        cnicNumber: baseData.cnicNumber || null,
        otpMobileNumber: baseData.otpMobileNumber || null,
        handlerType: baseData.handlerType || null,
        
        // Other legacy fields
        ...baseData
    };
};

/**
 * Get type-specific data based on request type
 */
export const getTypeSpecificData = (type, data) => {
    switch(type) {
        case 'NEW_MAPPING':
            return {
                isInitialMapping: true,
                mappingType: 'NEW'
            };
            
        case 'TRANSFER_OWNERSHIP':
            return {
                originalRequestId: data.originalRequestId,
                originalBdoId: data.originalBdoId,
                originalBdoName: data.originalBdoName,
                transferReason: data.transferReason || 'Ownership transfer',
                newLocationRequired: true
            };
            
        case 'OTP_CHANGE':
            return {
                oldOtpMobile: data.oldOtpMobile,
                newOtpMobile: data.newOtpMobile,
                changeReason: data.changeReason || 'OTP mobile number change'
            };
            
        case 'FAULTY_REPLACEMENT':
            return {
                faultyDeviceImei: data.faultyDeviceImei,
                replacementDeviceImei: data.replacementDeviceImei,
                faultDescription: data.faultDescription,
                faultReportDate: data.faultReportDate || Timestamp.now()
            };
            
        case 'DEVICE_RETURN':
            return {
                returnReason: data.returnReason,
                returnDate: data.returnDate || Timestamp.now(),
                deviceCondition: data.deviceCondition || 'Unknown'
            };
            
        default:
            return {};
    }
};

/**
 * Helper function to convert old request structure to new unified structure
 */
export const convertLegacyToUnified = (oldRequest) => {
    // Determine request type based on existing data
    let requestType = 'NEW_MAPPING'; // default
    if (oldRequest.type === 'Transfer') {
        requestType = 'TRANSFER_OWNERSHIP';
    }
    
    const baseData = {
        franchiseId: oldRequest.franchiseId,
        franchiseName: oldRequest.franchiseName,
        franchiseCode: oldRequest.franchiseCode,
        submittedBy: oldRequest.franchiseId,
        
        imei: oldRequest.imei,
        bdoId: oldRequest.bdoId,
        bdoName: oldRequest.bdoName,
        cnicNumber: oldRequest.cnicNumber,
        otpMobileNumber: oldRequest.otpMobileNumber,
        handlerType: oldRequest.handlerType,
        
        shopName: oldRequest.shopName,
        city: oldRequest.city,
        streetAddress: oldRequest.streetAddress,
        latitude: oldRequest.latitude,
        longitude: oldRequest.longitude,
        premiseRelationship: oldRequest.premiseRelationship,
        
        documents: oldRequest.documents || {}
    };
    
    const typeSpecificData = getTypeSpecificData(requestType, oldRequest);
    const newRequest = createUnifiedRequest(requestType, baseData, typeSpecificData);
    
    // Preserve original timestamps and status
    newRequest.createdAt = oldRequest.createdAt;
    newRequest.updatedAt = oldRequest.updatedAt;
    newRequest.status = oldRequest.status;
    
    return newRequest;
};
